[package]
name = "bin"
version = "0.0.3"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.4.6", features = [ "derive" ]}
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }

[build-dependencies]
specta = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }
