[workspace]
resolver = "2"
members = [
  "bin",
  "bin/proto",
]

[workspace.dependencies]
anyhow = "1.0.72"
dirs = "5.0.1"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.107"
specta = "1.0.5"
